In [31]:
from sklearn.datasets import load_diabetes

In [32]:
import pandas as pd
import numpy as np


In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
from sklearn.metrics import r2_score

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X,y=load_diabetes(return_X_y=True)

In [37]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [38]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [39]:
print(X.shape)

(442, 10)


In [40]:
print(y.shape)

(442,)


In [41]:
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2,random_state=2)

In [42]:
reg=LinearRegression()

In [43]:
reg.fit(X_train,y_train)

LinearRegression()

In [44]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [45]:
reg.intercept_

151.88331005254167

In [60]:
class GDRegressor:
  def __init__(self,learning_rate=0.01,epochs=100):
    self.learning_rate=learning_rate
    self.epochs=epochs
    self.coef_=None
    self.intercept_=None

  def fit(self,X_train,y_train):
    self.intercept_=0
    self.coef_=np.ones(X_train.shape[1])


    for i in range(self.epochs):
      y_=self.intercept_ + np.dot(X_train,self.coef_)
      y_net=y_train-y_
      self.intercept_=self.intercept_-(self.learning_rate*-2*np.mean(y_net))
      self.coef_=self.coef_ - (self.learning_rate*-2*(np.dot(y_net,X_train)/X_train.shape[0]))
    print(self.intercept_,self.coef_)
  def predict(self,X_test):
    return np.dot(X_test,self.coef_) + self.intercept_

In [61]:
gdr = GDRegressor(epochs=1000,learning_rate=0.5)

In [62]:
gdr.fit(X_train,y_train)

152.01351687661833 [  14.38990585 -173.7235727   491.54898524  323.91524824  -39.32648042
 -116.01061213 -194.04077415  103.38135565  451.63448787   97.57218278]


In [63]:
y_pred = gdr.predict(X_test)

In [64]:
r2_score(y_test,y_pred)

0.4534503034722803

In [ ]:
# class GDregressor:
#   def __init__(self,learning_rate=0.01,epochs=100):
#     self.learning_rate=learning_rate
#     self.epochs=epochs
#     self.coef_=None
#     self.intercept_=None

#   def fit(self,X_train,y_train):
#     self.intercept_=0
#     self.coef_=np.ones(X_train.shape[1])


#     for i in range(self.epochs):
#       y_=self.intercept + np.dot(X_train,self.coef_)
#       y_net=y_train-y_
#       self.intercept=self.intercept-(self.learning_rate*-2*np.mean(y_net))




#       self.coef_=self.coef_ - (self.learning*-2*np.mean(np.dot(y_net,X_train)))


In [49]:
np.ones(X_train.shape[1])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])